// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfVfnQ7wVBLJfcfDyH5a8D0LQfgE1YQp0',
    appId: '1:294954183165:web:d6bcb9709829a9b7365194',
    messagingSenderId: '294954183165',
    projectId: 'flutter-firebase-chat-fbd3c',
    authDomain: 'flutter-firebase-chat-fbd3c.firebaseapp.com',
    storageBucket: 'flutter-firebase-chat-fbd3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8r1Lc2YKs-5Q5N8HcNd4913utEULPTa8',
    appId: '1:294954183165:android:718994526537dade365194',
    messagingSenderId: '294954183165',
    projectId: 'flutter-firebase-chat-fbd3c',
    storageBucket: 'flutter-firebase-chat-fbd3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZEci8yXkLr5zorEVeD5vTrvHtLcusE0',
    appId: '1:294954183165:ios:58f7a94ef3ad8026365194',
    messagingSenderId: '294954183165',
    projectId: 'flutter-firebase-chat-fbd3c',
    storageBucket: 'flutter-firebase-chat-fbd3c.appspot.com',
    iosBundleId: 'com.example.firebaseChat',
    iosClientId:
        'com.googleusercontent.apps.294954183165-ncm3folubpkkn2ggvmebl99lb9cl2t34',
  );
}
